name: SPEC-0 Compliance Bot

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  spec0-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install requests packaging toml PyGithub

      - name: Debug environment values before action
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          echo "GITHUB_REPOSITORY=${{ github.repository }}"
          echo "SPEC0_DRY_RUN=false"

      - name: Run SPEC-0 Compliance Bot
        uses: Marcello-Sega/spec0-compliance-bot@v0.2
        with:
          path: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          dry_run: "false"
