- name: Run SPEC-0 Compliance Bot
  uses: Marcello-Sega/spec0-compliance-bot@v0.2
  with:
    path: .
    dry_run: "false"
    token: ${{ secrets.GITHUB_TOKEN }}

  env:
    GITHUB_REPOSITORY: ${{ github.repository }}
    
